### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by karlito62** [WordPress/wordpress-importer#126]
hi, 

my theme uses WordPress Importer it hasn't been updated for over two years and wordfence security notifies me that there is a security issue.
Could you please update the page : https://fr.wordpress.org/plugins/wordpress-importer/

on your support forum several users have the same problem
https://wordpress.org/support/topic/abandoned-plugin-60/

thank you in advance

**Comment by hpthatsme** [comment]
Have our requests been seen?  It's been over a week, no response.

**Comment by lhall-amphibee** [comment]
We are having issues with the PHP 8 compatibility which has been merged, but still not released. Is there still a maintainer ?

**Comment by iamkingsleyf** [comment]
Still no update, this is a critical plugin and yet still not developed

**Comment by dd32** [comment]
I've released version 0.8 which resolves this.
