### ISSUE TITLE
WP Version required bump seems unnecessary

### ISSUE THREAD

**Issue by smileBeda** [WordPress/wordpress-importer#135]
Might I ask what the reasoning behind the bump of minimally required WP version is?

> With WP 5.2 being the new minimum supported WP version, the polyfill for the `map_deep()` function is no longer needed.
> Similarly, the bowing out for the term meta import (on WP < 4.4) is also no longer needed.

Neither of both are a real cause.
- `map_deep()` has been around since WP 4.4 (thus the Minimal WP Version could just stay 4.4): https://developer.wordpress.org/reference/functions/map_deep/#changelog
- The term meta methods used in the code, as well have been around since 4.4

The mentioned reasons on the release post thus cannot be the justification of dropping all installs below 5.2, and specially since this is an "inbuilt" plugin (linked from the tools area), would it be possible to revert this in a future release, so it can stay around for older installs too?

**Comment by dd32** [comment]
See #95 for the discussion around it, notably, it's about the maintenance burden and ongoing maintenance of the plugin, rather than intentionally leaving older installs "out in the cold". Older WordPress versions could still use the older versions of the plugin, although we don't offer an easy way for those to be installed at present (or ever in those older versions).

Perhaps the question should be asked here, is what's the use-case needed for using the latest version of the importer on an older version of WordPress?  Or is it just the inability to install the older versions of the plugin easily?

Previously the minimum was WordPress 3.7, if we were to change anything here, I would suggest WordPress 4.0+ based on the [upcoming Security Support policy change](https://make.wordpress.org/security/2022/09/07/dropping-security-updates-for-wordpress-versions-3-7-through-4-0/).

**Comment by smileBeda** [comment]
The use case is, that an older install of WP will fail to install that importer from the tools menu.
Of course, they can manually download an older version, but as far I am concerned not many users to even know they can download older versions, and those who know, might refrain out of fear to be running outdated software equals unsafe software.

There are approx 38'675'000 websites still on pre 5.2 out of the alleged 455 millions running WP.
It's not nothing.

---

> if we were to change anything here, I would suggest WordPress 4.0+ based on the [upcoming Security Support policy change](https://make.wordpress.org/security/2022/09/07/dropping-security-updates-for-wordpress-versions-3-7-through-4-0/).

I think that would be the "conscious" thing to do, _specially_ since this is a "integrated" plugin, directly accessible in the WP Tools menu and not "obviously" a plugin to many users (they think it is just a feature to enable)

Thanks!

**Comment by dd32** [comment]
> The use case is, that an older install of WP will fail to install that importer from the tools menu.

Oddly enough, this isn't actually true - A WordPress 4.4 site can install through that tools menu, it does display a "This plugin hasn't been marked compatible with your version of WordPress" though.

I wasn't able to find it, but I believe the code which adds that restriction is in WordPress 4.9 or 5.0. Still lower than the minimum 5.2 here though.

> There are approx 38'675'000 websites still on pre 5.2 out of the alleged 455 millions running WP.
> It's not nothing.

It's not nothing, and I'm not going to argue the number of sites, but the question should be asked if any such old installations of WordPress would be attempting to install a new importer plugin, and whether we would want to support them doing so. My thought is that no, we don't. We want them to update their WordPress installation instead.

These older versions of WordPress are no longer officially supported, even the versions of WordPress Core that we perform security back-porting for (3.7/4.0) are not officially supported - only the latest stable branch is.

**Comment by jrfnl** [comment]
Just two more pennies for perspective: AFAIK the importer plugin is typically used when setting up a _new_ (WP) site, i.e to import posts which were previously in another website, either WP or based on another framework, and convert them to the (current) WP format.
Any _new_ site _should_ use the latest version of WP.

I understand there will be other usecases as well (merging multiple pre-existing blogs), but I would imagine that those are less frequent and even in that case, it is not that strange to expect the user to use a (more) recent version of WP.

Let's not forget WP 5.2 came out in 2019, so it's already three years old.

**Comment by dd32** [comment]
This was opened 2 years ago, and other than this there doesn't appear to have been any long-term issues.

I'm closing this issue for the purposes of cleaning up stale issues.
