### ISSUE TITLE
Importing images available only with query params fails

### ISSUE THREAD

**Issue by zpao** [WordPress/wordpress-importer#24]
If an image currently exists at a URL requiring query params then it can't be imported into WP. This is because the importer uses `basename()` on URLs, which keeps query params (https://github.com/WordPress/wordpress-importer/blob/b492a25dc61ca9c906b0d5e81a69f64d731d32ad/src/wordpress-importer.php#L983-L987, and a similar issue using `pathinfo`). Then WP has trouble using that as a filename and says it doesn't support the file extension IIRC.

Backstory: I'm exporting content that doesn't currently live in WordPress with the goal of importing into WP. Targeting WXR is our best compatibility layer so we're using that and then importing with this official importer. Unfortunately we can't drop the query params from our image urls. I understand my use case might not fit perfectly into expected output from a Wordpress export but it seems reasonable to try to support WXR as a generic target.

**Comment by ocean90** [comment]
Added #58 which should improve this a bit.
