### ISSUE TITLE
Not the version on wordpress.com

### ISSUE THREAD

**Issue by eugenekolo** [WordPress/wordpress-importer#25]
This isn't the version that's currently running on Wordpress.com.

Can t his be updated w/ that version, or where can I get that version? 

I ask, because I don't think the image attachment downloading is working. I can't debug it, because the version running on Wordpress.com isn't this one.

**Comment by dd32** [comment]
This is the open-source WordPress.org importer. WordPress.com may run a version of this, maybe an older version, probably a highly customised version.

Unfortunately as WordPress.com isn't open-source I'm unable to point you to any code which may be relevant to your issue.
