### ISSUE TITLE
Errors on Importing

### ISSUE THREAD

**Issue by Lunteer** [WordPress/wordpress-importer#26]
I get the following error when importing...
![image](https://user-images.githubusercontent.com/35562279/36074393-186ae402-0f48-11e8-912f-aa8e1ebc8ba5.png)

And after Import...
![image](https://user-images.githubusercontent.com/35562279/36074403-3a5c0226-0f48-11e8-852a-ae4b02062153.png)

Showing all errors as this is the only time it shows up.

Thanks

**Comment by dd32** [comment]
This should be fixed via #4 and #16 - which haven't been officially released yet, it'll be included in this weeks importer release.

**Comment by Lunteer** [comment]
Thanks! Should have searched first. Sorry
