### ISSUE TITLE
Add phpcs to Travis CI

### ISSUE THREAD

**Issue by GaryJones** [WordPress/wordpress-importer#32]
If/when #31 is merged, then the codebase will be passing PHPCS:

![screenshot 2018-03-03 14 17 40](https://user-images.githubusercontent.com/88371/36935375-0cf229ee-1eef-11e8-9227-b72a0f49872a.png)

Therefore, this could go into the `.travis.yml` file, so that future PRs and commits can be more likely to be following code standards too.

**Comment by jrfnl** [comment]
Why not include the travis setup in a separate commit in #31 ?

**Comment by GaryJones** [comment]
Because it's a separate scope.

**Comment by jrfnl** [comment]
Fixed in #75
