### ISSUE TITLE
Replace use of wp_get_http()

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/wordpress-importer#4]
`wp_get_http()` calls `@set_time_limit( 60 );` internally, which means the importer can fatal while importing large files. When the importer fatals, then some amount of user data is broken.

Originally https://core.trac.wordpress.org/ticket/34679

**Comment by lukecav** [comment]
https://github.com/boonebgorges/wordpress-importer/pull/5

**Comment by gerasimovdaniel** [comment]
#10
