### ISSUE TITLE
Indirect access to variables, PHP CodeSniffer error when checking PHP 7.2 compatibility

### ISSUE THREAD

**Issue by Varin6** [WordPress/wordpress-importer#43]
CodeSniffer included this in a report:

FILE: C:\xampp\htdocs\clientsite\wp-content\plugins\wordpress-importer\wordpress-importer.php

FOUND 1 ERROR AFFECTING 1 LINE

884 | ERROR | Indirect access to variables, properties and methods will be evaluated strictly in left-to-right order since PHP 7.0. Use curly braces to remove ambiguity.

Seems like an easy fix, just need to include curly braces.

**Comment by jrfnl** [comment]
Eh.. that was fixed ages ago. Please upgrade to the latest version (0.6.4).

**Comment by Varin6** [comment]
My bad, checked if I had the newest version on clients live site and I did, but then ran the CodeSniffer on local which didn't have the newest version....  Sorry!
