### ISSUE TITLE
Data from term meta are not importing.

### ISSUE THREAD

**Issue by h71** [WordPress/wordpress-importer#46]
This maybe related to another issue here: https://github.com/WordPress/wordpress-importer/issues/12

I have added some meta fields for category taxonomy and i'm not able to import them from tools.
I see that my term meta data are available in xml file.

```	
<wp:category>
	<wp:term_id>21</wp:term_id>
	<wp:category_nicename><![CDATA[book]]></wp:category_nicename>
	<wp:category_parent><![CDATA[]]></wp:category_parent>
	<wp:cat_name><![CDATA[Book]]></wp:cat_name>
	<wp:termmeta>
		<wp:meta_key><![CDATA[my_layout]]></wp:meta_key>
		<wp:meta_value><![CDATA[global]]></wp:meta_value>
	</wp:termmeta>
	<wp:termmeta>
		<wp:meta_key><![CDATA[_my_layout]]></wp:meta_key>
		<wp:meta_value><![CDATA[field_my_taxonomy_layout]]></wp:meta_value>
	</wp:termmeta>
	<wp:termmeta>
		<wp:meta_key><![CDATA[my_taxonomy_thumbnail_id]]></wp:meta_key>
		<wp:meta_value><![CDATA[10]]></wp:meta_value>
	</wp:termmeta>
	<wp:termmeta>
		<wp:meta_key><![CDATA[_my_taxonomy_thumbnail_id]]></wp:meta_key>
		<wp:meta_value><![CDATA[field_my_taxonomy_thumbnail_id]]></wp:meta_value>
	</wp:termmeta>
</wp:category>
```

WordPress Version: 5.0.1

WordPress Importer Version: 0.6.4

We are able to apply possible fixes and send PR and write tests. But, I see there are many PRs that are not merged yet.
Is this a dead repository? If yes, how and where I have to report issues? If not, you should know that this bug is affecting many users and they may loose their data.

Note: Any possible fixes and workaround is too much appreciated 🙏.

**Comment by djdmsr** [comment]
Termmeta imported but keys duplicated, and the duplicated is empty!

ex: with 2 terms for 2 tax (tint & secondary_tint) each term have 2 meta: one for a color (taxonomy prefixed tint_hex_color or secondary_tint_hex_color) and a second  (schema_wp_sameAs, which pose problem) which is common to both taxonomies.

	<wp:term>
		<wp:term_id><![CDATA[43008]]></wp:term_id>
		<wp:term_taxonomy><![CDATA[tint]]></wp:term_taxonomy>
		<wp:term_slug><![CDATA[rouge]]></wp:term_slug>
		<wp:term_name><![CDATA[Rouge]]></wp:term_name>
		<wp:termmeta><wp:meta_key><![CDATA[tint_hex_color]]></wp:meta_key><wp:meta_value><![CDATA[#ff0000]]></wp:meta_value></wp:termmeta>
		<wp:termmeta>
			<wp:meta_key><![CDATA[schema_wp_sameAs]]></wp:meta_key>
			<wp:meta_value><![CDATA[https://fr.wikipedia.org/wiki/Mod%C3%A8le:Palette_Teintes_de_rouge]]></wp:meta_value>
		</wp:termmeta>
	</wp:term>
	<wp:term>
		<wp:term_id><![CDATA[43009]]></wp:term_id>
		<wp:term_taxonomy><![CDATA[secondary_tint]]></wp:term_taxonomy>
		<wp:term_slug><![CDATA[vert]]></wp:term_slug>
		<wp:term_name><![CDATA[Vert]]></wp:term_name>
		<wp:termmeta><wp:meta_key><![CDATA[secondary_tint_hex_color]]></wp:meta_key><wp:meta_value><![CDATA[#00ff00]]></wp:meta_value></wp:termmeta>
		<wp:termmeta>
			<wp:meta_key><![CDATA[schema_wp_sameAs]]></wp:meta_key>
			<wp:meta_value><![CDATA[https://fr.wikipedia.org/wiki/Mod%C3%A8le:Palette_Teintes_de_vert]]></wp:meta_value>
		</wp:termmeta>
	</wp:term>

**Results after import in phpmyAdmin**: 
_Showing rows 0 -  5 (6 total, Query took 0.0005 seconds.)
SELECT * FROM wp_termmeta_

meta_id	term_id	meta_key	meta_value	
2353	3706	schema_wp_sameAs		
2354	3706	tint_hex_color	#ff0000	
2355	3706	schema_wp_sameAs	https://fr.wikipedia.org/wiki/Mod%C3%A8le:Palette_Teintes_de_rouge	
2356	3707	schema_wp_sameAs		
2357	3707	secondary_tint_hex_color	#00ff00	
2358	3707	schema_wp_sameAs	https://fr.wikipedia.org/wiki/Mod%C3%A8le:Palette_Teintes_de_vert	

result: schema_wp_sameAs	is not displaying correctly (empty) in columns at edit-tags.php
if I delete 2353 & 2356, everything becomes normal again.

I have more problems with a bigger file (1000 terms). All schema_wp_sameAs fields are empties after importation.

NB:
WordPress Version: 5.0.1
WordPress Importer Version: 0.6.4

Thank you for your attention.
