### ISSUE TITLE
Does not import every post in a category

### ISSUE THREAD

**Issue by iamkingsleyf** [WordPress/wordpress-importer#65]
Hi,

Recently we tried to export our article to another domain so we use this plugin https://wordpress.org/plugins/export-media-with-selected-content/ to add the images to article since we are exporting by category and by default wordpress does not add the images.... 

We found out that the ARTICLES NOT ALL are imported to the new site, it imports like 60% of the articles in some category, like we tried importing a 6 article category, only 2 were imported to the new site.

**Comment by ocean90** [comment]
At the moment, there is not enough information here to troubleshoot. Please continue in the support forums first: https://wordpress.org/support/topic/does-not-import-every-post-in-a-category/
