### ISSUE TITLE
Import issues with backslashes in serialized values for commentmeta.

### ISSUE THREAD

**Issue by stephdau** [WordPress/wordpress-importer#67]
If I use the standard WP Exporter on a site where Akismet (example) was used, there is some `commentmeta` data that gets exported, such as `akismet_history` records, that can contain PHP serialized data.

Because of the XML export format, those serialized values end-up being read as backslash-escaped values by PHP in `WP_Import::process_posts()`, when trying to run `maybe_unserialize()` [here](https://github.com/WordPress/wordpress-importer/blob/master/src/wordpress-importer.php#L821).

EG of those `akismet_history` records as seen be `commentmeta` processing part of importer:

- `'a:3:{s:4:\"time\";d:1573225357.883289;s:5:\"event\";s:9:\"check-ham\";s:4:\"user\";s:10:\"someuser\";}'`
- `'a:3:{s:4:\"time\";d:1573225662.52304;s:5:\"event\";s:15:\"status-approved\";s:4:\"user\";s:7:\"someotheruser\";}'`

What that leads to is that `maybe_unseriale()` returns false, which `add_comment_meta()` interprets as an empty value (so the `akismet_history` record gets created, but with an empty value).

Not sure if this should be done in the installer, or at the `maybe_unserialze()` level, but unescaping the value leads to the unserialization succeeding as expected: `$value = maybe_unserialize( stripslashes( $meta['value'] ) );`

EG when using `stripslashes()`:

- array (size=3)
  'time' => float 1573225459.2487
  'event' => string 'check-ham' (length=9)
  'user' => string 'someuser' (length=8)

**Comment by ocean90** [comment]
Seems to be the same issue which #57 has fixed for term meta, particular this line https://github.com/WordPress/wordpress-importer/pull/57/files#diff-16f92ba21465eac8836470c0ff3f6a5bL521.

The meta shouldn't get slashed here https://github.com/WordPress/wordpress-importer/blob/d7045b3c025f81f6e783aa4c04971ffdbd9ab853/src/wordpress-importer.php#L815.

**Comment by stephdau** [comment]
Yup, sounds legit. Running the importer with the same import file, but minus that `wp_slash()` solves the issue.

**Comment by ocean90** [comment]
Noting that the `wp_slash()` is needed for the other data since `wp_insert_comment()` expects data to be slashed.

I'll try to work on a test and fix for this based on #57.

**Comment by stephdau** [comment]
> I'll try to work on a test and fix for this based on #57.

Thank you. :)
