### ISSUE TITLE
no issue but the german language file

### ISSUE THREAD

**Issue by kk-qgis** [WordPress/wordpress-importer#81]
no issue but the german language file for the plugin
[pt-ocdi-de_DE.zip](https://github.com/WordPress/wordpress-importer/files/5358713/pt-ocdi-de_DE.zip)

**Comment by dd32** [comment]
Hi @kk-qgis,

The uploaded file appears to be a translation for another plugin, as per https://wordpress.org/support/topic/german-file/ can you submit this to https://github.com/awesomemotive/one-click-demo-import/issues instead?

Additionally, most WordPress plugins are translated through http://translate.wordpress.org/ - If you'd like to help translate some of the plugins you use, check out the Polyglots Handbook: https://make.wordpress.org/polyglots/handbook/

Thanks!
