### ISSUE TITLE
Replace Travis CI with GitHub Actions

### ISSUE THREAD

**Issue by ocean90** [WordPress/wordpress-importer#91]
Since Travis CI no longer runs builds for open source projects, the current [`.travis.yml`](https://github.com/WordPress/wordpress-importer/blob/7bbdcdfddd1ceecc6ec3fa2735aec3f11f7a88cb/.travis.yml#L1) config needs to be converted to one or more GitHub workflows.

With the switch we should also make sure that all current PHP versions are tested.

**Comment by jrfnl** [comment]
I'm looking into this.

An initial finding is that PHP 5.2 would not be easy to test anymore as it is not supported by the [best "setup PHP" action](https://github.com/marketplace/actions/setup-php-action).

Personally, I'd advocate for dropping support for PHP 5.2 by adding a `Requires PHP: 5.3` header and no longer testing on PHP 5.3.
