### ISSUE TITLE
Blank lines skipped in posts

### ISSUE THREAD

**Issue by dsnyder0pc** [WordPress/wordpress-importer#94]
I've observed that when importing posts with (intentional) embedded blank lines, the posts show up in the editor with the blank lines removed. I'm wondering if [this code change](https://github.com/WordPress/wordpress-importer/compare/0.6.4...0.7#diff-fbded9ce0f4cf9659a6895ef97e4e321ea4f4baaca594c6e12b66c4964dbcbbcR87-R89) is what is causing that:

![import xml file](https://www.dsnyder.ws-e.com/ts/vi.png)

Here's how this looks in the WordPress editor for "Free" customers on WordPress.com:

![import xml file](https://www.dsnyder.ws-e.com/ts/old.png)

As you can see, the blank lines are preserved. However, when I import the same content to a "Business" plan on WordPress.com, the blank lines appear to have been filtered out:

![import xml file](https://www.dsnyder.ws-e.com/ts/new.png)

My hypothesis is that, for blank lines, the PHP language evaluates $importline to False, causing the importer to skip over line 88. I have not tested this but may do so later this week. If so, I'll report back.

I'm in the process of importing 2,100 posts into a Business plan on WordPress.com, and the posts are basically unreadable with the missing whitespace. Thanks for having a look.

**Comment by dsnyder0pc** [comment]
In case the code sample is difficult to find from my hyperlink, it's these lines:

```
	87			if ( $in_multiline && $importline ) {
	88				$multiline_content .= $importline . "\n";
	89			}
```

The file is `src/parsers/class-wxr-parser-regex.php`

**Comment by dsnyder0pc** [comment]
After making this code change, the import works while preserving blank lines:

```
--- ./wp-content/plugins/wordpress-importer/parsers/class-wxr-parser-regex.php.dist 2021-01-31 21:29:35.318240822 +0000
+++ ./wp-content/plugins/wordpress-importer/parsers/class-wxr-parser-regex.php  2021-02-03 17:52:22.412001641 +0000
@@ -75,16 +75,19 @@
            // We don't want to have this line added to `$is_multiline` below.
            $importline        = '';
            $in_multiline      = $tag;
+           $is_tag_line       = true;

          } elseif ( false !== ( $pos = strpos( $importline, "</$tag>" ) ) ) {
            $in_multiline          = false;
            $multiline_content    .= trim( substr( $importline, 0, $pos ) );

            $this->{$handler[0]}[] = call_user_func( $handler[1], $multiline_content );
+         } else {
+           $is_tag_line       = false;
          }
        }

-       if ( $in_multiline && $importline ) {
+       if ( $in_multiline && ! $is_tag_line ) {
          $multiline_content .= $importline . "\n";
        }
      }
```

**Comment by dsnyder0pc** [comment]
@jrfnl - What do you think of this change? I could submit a PR if that would be helpful.

**Comment by jrfnl** [comment]
@dsnyder0pc As this seems to concern wordpress.com, your first point of contact should be Automattic. I have no clue whether this plugin is the importer they use or if they use a different or customized version. Let alone what the difference is between the importers on different versions of their platform, so I suggest you contact them about this.

**Comment by dsnyder0pc** [comment]
@jrfnl - Thanks for your reply. Based on my experience so far, it seems that WordPress.com does use this importer. The screenshots above were taken after my import to a Business plan on WordPress.com.

My workaround is to just sftp the modified file to WordPress.com, but I thought you might be interested in fixing this logic bug.

The `$importline` variable can evaluate to `False` in PHP both because it's explicitly set to an empty string and unintentionally, in the case of blank lines.

**Comment by dsnyder0pc** [comment]
I should add that I have been speaking to WordPress support, and I made them aware of the issue that I've opened up here and the workaround/fix I've proposed.

**Comment by jrfnl** [comment]
As I said before, without even knowing whether this plugin is used by wordpress.com, let alone which version(s) and what the difference is between their install on the Free versus the Business platform, there is nothing to base any changes on.

Basically without a lot more information, there is nothing to be done.

Oh and just FYI: I'm not the maintainer of this plugin, so pinging me by nickname or presuming anything about my interest in this plugin is kind of grating.

**Comment by dsnyder0pc** [comment]
My apologies. Who is the maintainer?

**Comment by dsnyder0pc** [comment]
@ocean90 - Can you help me find the owner of this plugin? I reached out to the most recent comitter, but apparently that was not a great idea. Thanks.

**Comment by yoavf** [comment]
@dsnyder0pc thanks for opening this issue and the PR!

Regarding the WordPress.com mention - I'll try to clarify as an employee of Automattic: on WordPress.com we run the latest released version of this core WP Importer for sites that have the ability to install plugins (=our business plan). For other sites, we use a different importer that has been optimized for our multisite install (and where the bug mentioned here does not appear to exist). 

@dsnyder0pc I'll try to confirm this issue against core WordPress, and review the PR.
